OIDC Api management
dotkom/onlineweb4 pull request #2560
Opened 2020-10-18 20:46 UTC by FluidSense

## Description of changes

OIDC Clients are the main way we allow users access to data through the API.
Thus, it should be possible to create a management app for OIDC Clients which would allow users to log in and edit configuration for their own clients. 

The OIDC-package that we use (`django-oidc-provider`) sets ID and secret through the admin form. This PR adds these secrets on `Create` and `Update` if the client is `confidential` to allow for a management app to also support creations of new clients.

## Code Checklist

- [ ] I have added tests
- [ ] I have provided documentation

## To-Do

- [ ] Protect the endpoint with a TokenHasScope (from `oauth2_provider`, oh the irony) to regulate whom can create apps which access sensitive client data.  
- [ ] Add tests.

2020-10-30 19:24 UTC, FluidSense commented
Perhaps we should add scope protection, but as of now, very very few of our apps are using it and our OIDC-provider does not support DRF. I feel that it is thus outside of the scope of this PR

2020-11-01 17:46 UTC, oleast requested changes
🇰🇿

2020-11-01 17:46 UTC, oleast commented on apps/online_oidc_provider/serializers.py
> +        print(data)
Print

2020-11-01 17:47 UTC, FluidSense commented on apps/online_oidc_provider/serializers.py
> +        print(data)
_damn, you're good_

2020-11-01 18:16 UTC, oleast approved these changes

2020-11-01 19:29 UTC, merged